declare const MOUSE_ENUM_OFFSET: number

/** @compileMembersOnly  */
declare enum Pop3InputKey
{
    LB_KEY_NONE = 0,
    LB_KEY_ESC,
    LB_KEY_MINUS,
    LB_KEY_NUM_MINUS,
    LB_KEY_EQUAL,
    LB_KEY_NUM_PLUS,
    LB_KEY_BACKSPACE,
    LB_KEY_TAB,
    
    LB_KEY_0 = 0x30,
    LB_KEY_1 = 0x31,
    LB_KEY_2 = 0x32,
    LB_KEY_3 = 0x33,
    LB_KEY_4 = 0x34,
    LB_KEY_5 = 0x35,
    LB_KEY_6 = 0x36,
    LB_KEY_7 = 0x37,
    LB_KEY_8 = 0x38,
    LB_KEY_9 = 0x39,

    LB_KEY_A = 0x41,
    LB_KEY_B = 0x42,
    LB_KEY_C = 0x43,
    LB_KEY_D = 0x44,
    LB_KEY_E = 0x45,
    LB_KEY_F = 0x46,
    LB_KEY_G = 0x47,
    LB_KEY_H = 0x48,
    LB_KEY_I = 0x49,
    LB_KEY_J = 0x4A,
    LB_KEY_K = 0x4B,
    LB_KEY_L = 0x4C,
    LB_KEY_M = 0x4D,
    LB_KEY_N = 0x4E,
    LB_KEY_O = 0x4F,
    LB_KEY_P = 0x50,
    LB_KEY_Q = 0x51,
    LB_KEY_R = 0x52,
    LB_KEY_S = 0x53,
    LB_KEY_T = 0x54,
    LB_KEY_U = 0x55,
    LB_KEY_V = 0x56,
    LB_KEY_W = 0x57,
    LB_KEY_X = 0x58,
    LB_KEY_Y = 0x59,
    LB_KEY_Z = 0x5A,
    
    LB_KEY_LSBRACKET,
    LB_KEY_RSBRACKET,
    LB_KEY_RETURN,
    LB_KEY_NUM_ENTER,
    LB_KEY_LCONTROL,
    LB_KEY_COLON,
    LB_KEY_QUOTE,
    LB_KEY_QUOTE2,
    LB_KEY_LSHIFT,
    LB_KEY_HASH,
    LB_KEY_COMMA,
    LB_KEY_DOT,
    LB_KEY_NUM_DOT,
    LB_KEY_SLASH,
    LB_KEY_RSHIFT,
    LB_KEY_LALT,
    LB_KEY_SPACE,
    LB_KEY_CAPS,
    
    LB_KEY_F1 = 0x70,
    LB_KEY_F2 = 0x71,
    LB_KEY_F3 = 0x72,
    LB_KEY_F4 = 0x73,
    LB_KEY_F5 = 0x74,
    LB_KEY_F6 = 0x75,
    LB_KEY_F7 = 0x76,
    LB_KEY_F8 = 0x77,
    LB_KEY_F9 = 0x78,
    LB_KEY_F10 = 0x79,
    LB_KEY_F11 = 0x7A,
    LB_KEY_F12 = 0x7B,
    
    LB_KEY_NUM_0,
    LB_KEY_NUM_INSERT,
    LB_KEY_NUM_1,
    LB_KEY_NUM_2,
    LB_KEY_NUM_3,
    LB_KEY_NUM_4,
    LB_KEY_NUM_5,
    LB_KEY_NUM_6,
    LB_KEY_NUM_7,
    LB_KEY_NUM_8,
    LB_KEY_NUM_9,
    LB_KEY_NUM_SLASH,

    LB_KEY_NUM_ASTERISK,
    LB_KEY_NUM_LOCK,
    LB_KEY_SCROLL_LOCK,
    LB_KEY_BACKSLASH,
    
    LB_KEY_RCONTROL,
    LB_KEY_PRINT_SCR,
    LB_KEY_RALT,
    LB_KEY_BREAK,
    LB_KEY_PAUSE,
    LB_KEY_HOME,
    LB_KEY_UP,
    LB_KEY_PGUP,
    LB_KEY_LEFT,
    LB_KEY_RIGHT,
    LB_KEY_END,
    LB_KEY_DOWN,
    LB_KEY_PGDN,
    LB_KEY_INSERT,
    LB_KEY_DELETE,
    LB_KEY_NUM_DELETE,

    LB_KEY_MOUSE0,
    LB_KEY_MOUSE1,
    LB_KEY_MOUSE2,
    LB_KEY_MOUSE3,
    LB_KEY_MOUSE4,
    LB_KEY_MAX,

    MAX_KEYS,

    LB_KEY_MOUSE_LEFT,
    LB_KEY_MOUSE_RIGHT,
    LB_KEY_MOUSE_MIDDLE
}